### ISSUE TITLE
hooks code in jsday2019?

### ISSUE THREAD

**Issue by shengxinjing** [pomber/didact#10]
is there hooks code in jsday2019 slide?
thank you very much

**Comment by pomber** [comment]
Are you looking for the code from the jsday2019 talk? it's here: https://github.com/pomber/didact/blob/hooks/didact.js

**Comment by shengxinjing** [comment]
thank you for reply
can i get the mdx slide?

**Comment by pomber** [comment]
Slides: https://buildyourownreact.now.sh/

**Comment by shengxinjing** [comment]
thanks very much

**Comment by shengxinjing** [comment]
awsome slides
how can i write this page by code-sufer？
https://buildyourownreact.now.sh/14
