### ISSUE TITLE
Confusing re-assignment

### ISSUE THREAD

**Issue by joshuaalpuerto** [pomber/didact#20]
Hi, thank you for your tutorial I am enjoying it. So far so good but I have confusion on [this part](https://github.com/pomber/didact/blob/master/didact.js#L291-L297).

```js
    if (index === 0) {
      wipFiber.child = newFiber
    } else if (element) {
     // even we set this we are still going to overwrite it. so what's the point?
      prevSibling.sibling = newFiber
    }
   // in here we are overwriting the whole object
   // that means `prevSibling.sibling` will be gone
    prevSibling = newFiber
```

Cheers!

**Comment by al3ksandrsafonov** [comment]
It's not a variable, so we don't overwrite nothing! It is an object, so we just change a link on it.
When index = 0 we have in memory the object newFiber_0 and 3 links on it:
newFiber  => newFiber_0
wipFiber.child  => newFiber_0 after operation wipFiber.child = newFiber
prevSibling  => newFiber_0 after prevSibling = newFiber
Then index = 1 and we have in memory 2 objects(newFiber_0 and newFiber_1) and 3 links:
newFiber  => newFiber_1
wipFiber.child  => newFiber_0
prevSibling  => newFiber_0 
The operation prevSibling.sibling = newFiber adds the link on the object newFiber_1 to the object newFiber_0, so we have:
newFiber  => newFiber_1
wipFiber.child  => newFiber_0
wipFiber.child.sibling  => newFiber_1
prevSibling  => newFiber_0 
After operation prevSibling = newFiber:
newFiber  => newFiber_1
wipFiber.child  => newFiber_0
wipFiber.child.sibling  => newFiber_1
prevSibling  => newFiber_1 
Then index = 2 and we have in memory 3 objects(newFiber_0, newFiber_1, newFiber_2) and links:
newFiber  => newFiber_2
wipFiber.child  => newFiber_0
wipFiber.child.sibling  => newFiber_1
wipFiber.child.sibling.sibling  => newFiber_2
prevSibling  => newFiber_2
And so on...

**Comment by joshuaalpuerto** [comment]
Wow @al3ksandrsafonov Thank you for you explanation I get it now.  Basically it mutates the `wipFiber.child` since `prevSibling` has link to the `newFiber` object.

**Comment by asvencoop** [comment]
@joshuaalpuerto @al3ksandrsafonov , thanks for you explanation,  the key  point is object is reference type.
