### ISSUE TITLE
useState not work in multiple case (with setTimeout)

### ISSUE THREAD

**Issue by shadowvzs** [pomber/didact#23]
@pomber 
### 1. Issue with setTimeout

```jsx
const element = <Test />
const container = document.getElementById("root")
render(element, container)
```

```jsx
const Test = (): JSX.Element => {
    document.title = `Home Page`;

    const [s, setS] = useState(10);

    setTimeout(() => {
        setS(Math.random());   // result is error in this moment
    }, 5000);

    return (
        <div>
            <h1 onClick={() => setS(c => c + 1)}>
                Count: {s}
            </h1>
        </div>
    );
}
```

```jsx
export function useState(initial) {
    ...........
    actions.forEach(action => hook.state = action(hook.state)); // here the action is a number and not the function which should set the value
    // TypeError: action is not a function 
    ........
```

### 2. Issue with setTimeout

same code just with directly called element

```jsx
const element = Test();
const container = document.getElementById("root")
render(element, container)
```

```jsx
export function useState(initial) {
    // wipFiber is     ##@@null
    const oldHook = wipFiber.alternate && wipFiber.alternate.hooks && wipFiber.alternate.hooks[hookIndex];
```

use state not work if i call it from set timeout / interval

**Comment by pomber** [comment]
Not sure if you figured it out, in didact setState only accepts a function as the parameter. So, you shouldn't use `setState(newState)` but `setState(oldState => newState)`.

**Comment by shadowvzs** [comment]
> Not sure if you figured it out, in didact setState only accepts a function as the parameter. So, you shouldn't use `setState(newState)` but `setState(oldState => newState)`.

yeah, ty i figured out thats why i closed, i make few experiment with stats in this weekend :) 
this was my fault, i didn't checked well, still i found other issue if i use multiple functional component with stat in host component which also have state, maybe if you got time you could check this https://github.com/pomber/didact/issues/24
