### ISSUE TITLE
Minor issue in reconciler commitWork

### ISSUE THREAD

**Issue by leiyangyou** [pomber/didact#4]
Hi, 

again, thanks for this very concise and understandable introduction.

One minor issue is this, it looks like

```javascript
  } else if (fiber.effectTag == UPDATE) { 
```

should have been 

```javascript
  } else if (fiber.effectTag == UPDATE && fiber.tag == HOST_COMPONENT) { 
```

**Comment by mindplay-dk** [comment]
Looks like this was [fixed](https://github.com/pomber/didact/blob/master/src/reconciler.js#L266) but never closed?
